### PR TITLE
Making tests pass using NCrunch

### PR DESCRIPTION
**Pull request by AlbertoMonteiro**
I use NCrunch as test runner, and some test that are based on path like **MetricsCalculationPerformanceTest** they were breaking because NCrunch doesn't use same directory that solution are in.

### CODE REVIEW

**Comment by jjrdk** [comment]
There's a little too much going on in this PR. As far as I can see the only NCrunch related change is where you set the current directory in the performance test.

Honestly I'd prefer that you keep the NCrunch related stuff on a separate branch as it may not be relevant for a lot of consumers.

**Comment by AlbertoMonteiro** [comment]
Hi Jacob, sorry but I didn't understand this: *There's a little too much going on in this PR*.
Can you explain me?

About NCrunch related changes, you are right, I just change the current directory because NCrunch doesn't use assemblies/code in project folder, it copies to another location.

But about not relevant for a lot of consumers I didn't understand.
What do you call consurmers? People who use this by nuget package [Roslyn Code Analysis](https://www.nuget.org/packages/ArchiMetrics.Analysis/0.14.1-beta)?
If so, these people will not be affected. Since you doesn't deploy any related test stuff.

The question of relevance is debatable, you put some powershell scripts to do a custom build, which is related code updating the nuget package, I being a possible contributor, do not think that is relevant to me.

People who want to download source code and do something, will just download more one package, the "NCrunch.Framework" package, that is just 155 KB (159.565 bytes).

**Comment by jjrdk** [comment]
What I mean by 'too much going on' is that there are major changes to the project files (almost complete replacement, according to the diff viewer) without any noticeable reason. The .gitignore file also has a significant amount of changes which I can only assume relate to the files generated by NCrunch.

More importantly is the fact that you wish to include NCrunch into the main branch. NCrunch is a commercial tool. On top of the 155KB you mention it also requires a license. This makes it inappropriate for a code base which is intended to be free and open source. This is why I suggest that you maintain a separate NCrunch branch for yourself.

**Comment by AlbertoMonteiro** [comment]
I asked the owner of NCrunch about license, and he said that:

----------------------

Legally there isn't an issue with including the changes for NCrunch (and the reference to NCrunch.Framework). NCrunch is a productivity tool and is licensed as such .. it isn't a commercial library.

If referencing NCrunch.Framework in the project file is creating some friction, know that you can avoid this by simply writing the NCrunch.Framework.Environment.GetOriginalProjectPath() method in your own code. I've included the source code for this method below:

```csharp
public static string GetOriginalProjectPath()
{
    return Environment.GetEnvironmentVariable("NCrunch.OriginalProjectPath");
}
```

-------------------------

If I commint some modification like that below, would you allow? 

```csharp
[SetUp]
public void Setup()
{
    _calculator = new ProjectMetricsCalculator(new CodeMetricsCalculator());
#if NCRUNCH
    var directoryName = System.IO.Path.Combine(System.IO.Path.GetDirectoryName(GetOriginalProjectPath()), "bin", "Debug");
    System.IO.Directory.SetCurrentDirectory(directoryName); 
#endif
}

#if NCRUNCH
public static string GetOriginalProjectPath()
{
    return Environment.GetEnvironmentVariable("NCrunch.OriginalProjectPath");
} 
#endif
```

**Comment by AlbertoMonteiro** [comment]
@jjrdk any comment?

**Pull request closed without merging**
